export const routes = {
  home: "/",
  dashboardMy: "/dashboard/my",
  dashboardAll: "/dashboard/all",
  templates: "/templates",
  organizations: "/organizations",
  formResponsesById: "/dashboard/forms/:id/responses",
  formResponses: (id: string) => `/dashboard/forms/${id}/responses`,
  formResponsesHtmlById: "/dashboard/forms/:id/responses/html",
  formResponsesHtml: (id: string) => `/dashboard/forms/${id}/responses/html`,
  surveyById: "/form/:id",
  survey: (id: string) => `/form/${id}`,
  legacySurveyById: "/survey/:id",
  builder: "/builder",
  builderById: "/builder/:id",
  builderEdit: (id: string) => `/builder/${id}`,
  users: "/users",
  login: "/login",
} as const;
