import { expect, test } from "@playwright/test";
import { openSurveyApp } from "./fixtures/surveyApp";

test("section titles save and render, while only section titles and expressions default to optional", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  const { formId, form, pageErrors } = await openSurveyApp(page, { responseCount: 0, elements: [] });
  await page.goto(`/builder/${formId}`);
  await expect(page.locator(".builder-host")).toBeVisible();
  await expect(page.locator(".svc-creator")).toBeVisible();
  const toolbox = page.locator(".svc-toolbox");
  await expect(toolbox.locator(".svc-toolbox__item").first()).toContainText("Название раздела");
  await expect(toolbox.locator(".svc-toolbox__item").first().locator("use")).toHaveAttribute("xlink:href", /sectiontitle/);
  await toolbox.getByText("Название раздела", { exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Обязательный?", exact: true })).toHaveCount(0);
  const headingTitle = "Информационная безопасность";
  await page.getByRole("textbox", { name: "Название раздела", exact: true }).getByRole("textbox").fill(headingTitle);
  await toolbox.getByText("Текст", { exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Обязательный?", exact: true }).first()).toBeChecked();
  await toolbox.getByText("Расширенные", { exact: true }).click();
  await toolbox.getByText("Выражение", { exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Обязательный?", exact: true })).toHaveCount(1);
  await page.getByRole("button", { name: "Сохранить опрос", exact: true }).click();
  await expect.poll(() => form.schema.pages[0].elements.length).toBe(3);
  const elements = form.schema.pages[0].elements;
  const heading = elements.find(element => element.type === "sectiontitle")!;
  const expression = elements.find(element => element.type === "expression")!;
  const text = elements.find(element => element.type === "text")!;
  expect(heading).toBeDefined();
  expect(heading.isRequired ?? false).toBe(false);
  expect(expression.isRequired ?? false).toBe(false);
  expect(text.isRequired).toBe(true);
  expect(heading.title).toBe(headingTitle);
  await page.goto(`/builder/${formId}`);
  await expect(page.locator(".svc-creator")).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("section-title-builder.png"), fullPage: true });
  await page.getByRole("button", { name: /^Сменить тему/ }).click();
  await page.locator('[data-theme-option="graphite"]').click();
  await expect(toolbox.locator(".svc-toolbox__item").first().locator("svg")).toHaveCSS("color", "rgb(245, 245, 245)");
  await page.screenshot({ path: testInfo.outputPath("section-title-builder-dark.png"), fullPage: true });
  await page.getByText("Превью", { exact: true }).click();
  await expect(page.getByTestId("builder-preview-tab").getByText(heading.title!, { exact: true })).toBeVisible();
  await page.goto(`/form/${formId}`);
  await expect(page.getByText(heading.title!, { exact: true })).toBeVisible();
  await expect(page.getByRole("textbox", { name: text.title ?? text.name, exact: true })).toBeEditable();
  await expect(page.getByRole("textbox", { name: heading.title, exact: true }).locator("input, textarea")).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("section-title-form.png"), fullPage: true });
  expect(pageErrors).toEqual([]);
});
